<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>grpid3</groupId>
  <artifactId>Proj_selenium_TestNG</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
	  <dependency>
	        <groupId>org.testng</groupId>
	        <artifactId>testng</artifactId>
	        <version>7.9.0</version>
	        <scope>test</scope>
	   </dependency>
		<dependency>
		    <groupId>org.slf4j</groupId>
		    <artifactId>slf4j-simple</artifactId>
		    <version>1.7.36</version>
	   </dependency>

   </dependencies>	
   
   
   
   <build>
    <plugins>
      <!-- Surefire plugin to run TestNG suite -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.1.2</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>src/test/resources/testng.xml</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
    </plugins>
  </build>
  
</project>